# Exact feature mapping between SDSS GZ2 and DECaLS Galaxy Zoo catalogs
# Generated automatically - do not edit manually

SDSS_TO_DECALS = {
    'dec': 'dec',
    'dr7objid': 'iauname',
    'ra': 'ra',
    't01_smooth_or_features_a01_smooth_debiased': 'smooth-or-featured_smooth_debiased',
    't01_smooth_or_features_a01_smooth_fraction': 'smooth-or-featured_smooth_fraction',
    't01_smooth_or_features_a02_features_or_disk_debiased': 'smooth-or-featured_featured-or-disk_debiased',
    't01_smooth_or_features_a02_features_or_disk_fraction': 'smooth-or-featured_featured-or-disk_fraction',
    't01_smooth_or_features_a03_star_or_artifact_debiased': 'smooth-or-featured_artifact_debiased',
    't01_smooth_or_features_a03_star_or_artifact_fraction': 'smooth-or-featured_artifact_fraction',
    't02_edgeon_a04_yes_debiased': 'disk-edge-on_yes_debiased',
    't02_edgeon_a04_yes_fraction': 'disk-edge-on_yes_fraction',
    't02_edgeon_a05_no_debiased': 'disk-edge-on_no_debiased',
    't02_edgeon_a05_no_fraction': 'disk-edge-on_no_fraction',
    't03_bar_a06_bar_debiased': 'bar_yes_debiased',
    't03_bar_a06_bar_fraction': 'bar_yes_fraction',
    't03_bar_a07_no_bar_debiased': 'bar_no_debiased',
    't03_bar_a07_no_bar_fraction': 'bar_no_fraction',
    't04_spiral_a08_spiral_debiased': 'has-spiral-arms_yes_debiased',
    't04_spiral_a08_spiral_fraction': 'has-spiral-arms_yes_fraction',
    't04_spiral_a09_no_spiral_debiased': 'has-spiral-arms_no_debiased',
    't04_spiral_a09_no_spiral_fraction': 'has-spiral-arms_no_fraction',
    't05_bulge_prominence_a10_no_bulge_debiased': 'bulge-size_none_debiased',
    't05_bulge_prominence_a10_no_bulge_fraction': 'bulge-size_none_fraction',
    't05_bulge_prominence_a12_obvious_debiased': 'bulge-size_obvious_debiased',
    't05_bulge_prominence_a12_obvious_fraction': 'bulge-size_obvious_fraction',
    't05_bulge_prominence_a13_dominant_debiased': 'bulge-size_dominant_debiased',
    't05_bulge_prominence_a13_dominant_fraction': 'bulge-size_dominant_fraction',
    't07_rounded_a16_completely_round_debiased': 'how-rounded_completely_debiased',
    't07_rounded_a16_completely_round_fraction': 'how-rounded_completely_fraction',
    't07_rounded_a17_in_between_debiased': 'how-rounded_in-between_debiased',
    't07_rounded_a17_in_between_fraction': 'how-rounded_in-between_fraction',
    't07_rounded_a18_cigar_shaped_debiased': 'how-rounded_cigar-shaped_debiased',
    't07_rounded_a18_cigar_shaped_fraction': 'how-rounded_cigar-shaped_fraction',
    't09_bulge_shape_a25_rounded_debiased': 'edge-on-bulge_rounded_debiased',
    't09_bulge_shape_a25_rounded_fraction': 'edge-on-bulge_rounded_fraction',
    't09_bulge_shape_a26_boxy_debiased': 'edge-on-bulge_boxy_debiased',
    't09_bulge_shape_a26_boxy_fraction': 'edge-on-bulge_boxy_fraction',
    't09_bulge_shape_a27_no_bulge_debiased': 'edge-on-bulge_none_debiased',
    't09_bulge_shape_a27_no_bulge_fraction': 'edge-on-bulge_none_fraction',
    't10_arms_winding_a28_tight_debiased': 'spiral-winding_tight_debiased',
    't10_arms_winding_a28_tight_fraction': 'spiral-winding_tight_fraction',
    't10_arms_winding_a29_medium_debiased': 'spiral-winding_medium_debiased',
    't10_arms_winding_a29_medium_fraction': 'spiral-winding_medium_fraction',
    't10_arms_winding_a30_loose_debiased': 'spiral-winding_loose_debiased',
    't10_arms_winding_a30_loose_fraction': 'spiral-winding_loose_fraction',
    't11_arms_number_a31_1_debiased': 'spiral-arm-count_1_debiased',
    't11_arms_number_a31_1_fraction': 'spiral-arm-count_1_fraction',
    't11_arms_number_a32_2_debiased': 'spiral-arm-count_2_debiased',
    't11_arms_number_a32_2_fraction': 'spiral-arm-count_2_fraction',
    't11_arms_number_a33_3_debiased': 'spiral-arm-count_3_debiased',
    't11_arms_number_a33_3_fraction': 'spiral-arm-count_3_fraction',
    't11_arms_number_a34_4_debiased': 'spiral-arm-count_4_debiased',
    't11_arms_number_a34_4_fraction': 'spiral-arm-count_4_fraction',
    't11_arms_number_a36_more_than_4_debiased': 'spiral-arm-count_more-than-4_debiased',
    't11_arms_number_a36_more_than_4_fraction': 'spiral-arm-count_more-than-4_fraction',
}

DECALS_TO_SDSS = {v: k for k, v in SDSS_TO_DECALS.items()} 