# Galaxy Sommelier Head Training Configuration

# Data paths
data:
  scratch_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data"
  sdss_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/sdss"
  desi_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/desi"
  hst_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/hst"
  processed_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/processed"
  catalogs_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs"
  catalog_name: "gz2_master_catalog_corrected.csv"  # Use corrected catalog with 240k galaxies

# Model configuration
model:
  name: "facebook/dinov2-base"
  num_outputs: 74  # Galaxy Zoo 2 vote fractions (all fraction columns)
  dropout_rate: 0.2
  freeze_backbone: true

# Training parameters
training:
  batch_size: 32
  learning_rate: 1e-4
  num_epochs: 5
  warmup_steps: 1000
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  
# Data processing
preprocessing:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
# Augmentation
augmentation:
  rotation_degrees: 180
  horizontal_flip: true
  vertical_flip: true
  brightness_factor: 0.2
  contrast_factor: 0.2

# Galaxy Zoo tasks
galaxy_zoo_tasks:
  t01:
    responses: ["smooth", "features_or_disk", "star_or_artifact"]
    description: "Is the galaxy smooth and rounded, or does it have features?"
  t02:
    responses: ["edge_on_yes", "edge_on_no"]
    description: "Could this be a disk viewed edge-on?"
  t03:
    responses: ["bar_yes", "bar_no"]
    description: "Is there a bar feature through the center of the galaxy?"
  t04:
    responses: ["spiral_yes", "spiral_no"]
    description: "Is there any sign of a spiral arm pattern?"
  t05:
    responses: ["no_bulge", "obvious_bulge", "dominant_bulge"]
    description: "How prominent is the central bulge?"

# Experiment tracking
wandb:
  project: "galaxy-sommelier"
  entity: "sihany"  # Set to your wandb username/team
  log_freq: 100

# Hardware
device: "cuda"
num_workers: 4
pin_memory: true

# Logging
logging:
  level: "INFO"
  save_frequency: 5  # Save model every N epochs 