# Galaxy Sommelier Max Overlap Full Fine-tuning Configuration

# Data paths
data:
  scratch_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data"
  sdss_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/sdss"
  decals_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/decals"
  processed_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/processed"
  sdss_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/max_overlap_catalogs/sdss_max_overlap_training_catalog.csv"
  decals_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/max_overlap_catalogs/decals_max_overlap_training_catalog.csv"

# Max Overlap dataset configuration
mixed_data:
  use_mixed_dataset: true
  dataset_name: "MaxOverlapDataset"
  feature_set: "sdss"

# Model configuration
model:
  name: "facebook/dinov2-base"
  num_outputs: 52 
  dropout_rate: 0.2
  freeze_backbone: false  # Fine-tuning: unfreeze backbone

# Training parameters for full fine-tuning (same as mixed)
training:
  batch_size: 16  # Reduce batch size since full model uses more memory
  learning_rate: 1e-5  # Lower LR for backbone fine-tuning
  backbone_lr: 5e-6  # Even lower LR for pre-trained backbone
  head_lr: 1e-4  # Higher LR for classification head
  num_epochs: 10  # More epochs for full fine-tuning
  warmup_steps: 2000  # More warmup for stable training
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  
# Learning rate scheduling
lr_schedule:
  type: "cosine_with_warmup"
  warmup_ratio: 0.1  # 10% of training for warmup
  min_lr_ratio: 0.01  # Minimum LR as 1% of initial
  
# Data processing
preprocessing:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
# Augmentation (more aggressive for full fine-tuning)
augmentation:
  rotation_degrees: 180
  horizontal_flip: true
  vertical_flip: true
  brightness_factor: 0.3  # Slightly more aggressive
  contrast_factor: 0.3
  gaussian_blur: true  # Add blur augmentation
  gaussian_noise: true  # Add noise augmentation

# Experiment tracking
wandb:
  project: "galaxy-sommelier"
  entity: "sihany"
  log_freq: 50  # Log more frequently
  tags: ["max_overlap", "sdss_decals", "full_finetuning", "unfrozen_backbone"]

# Hardware
device: "cuda"
num_workers: 4
pin_memory: true

# Paths for outputs
checkpoint_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/models/max_overlap"
results_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/results/max_overlap"

# Initialization - start from head-trained model
pretrained_checkpoint: "/pscratch/sd/s/sihany/galaxy-sommelier-data/models/max_overlap/best_model.pt"

# Logging
logging:
  level: "INFO"
  save_frequency: 2  # Save model every 2 epochs
  
# Early stopping
early_stopping:
  patience: 3  # Stop if no improvement for 3 epochs
  min_delta: 0.001  # Minimum improvement threshold
  monitor: "val_correlation"  # Monitor validation correlation 