# Galaxy Sommelier Mixed High Quality Configuration - STANDARDIZED to 26 features

# Data paths
data:
  scratch_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data"
  sdss_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/sdss"
  decals_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/decals"
  desi_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/desi"
  hst_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/hst"
  processed_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/processed"
  catalogs_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs"
  catalog_name: "gz2_master_catalog_corrected.csv"
  
# Mixed dataset configuration - STANDARDIZED to 26 features
mixed_data:
  sdss_fraction: 0.5  # 50% SDSS, 50% DECaLS
  use_mixed_dataset: true
  feature_set: "standard_26"  # Use standardized 26-feature mapping
  quality_filter: true  # Enable high quality filtering

# Model configuration - STANDARDIZED to 26 outputs
model:
  name: "facebook/dinov2-base"
  num_outputs: 26  # STANDARDIZED: All models use same 26 features
  dropout_rate: 0.2
  freeze_backbone: false  # Full finetuning: unfreeze backbone

# Training parameters for full fine-tuning
training:
  batch_size: 16  # Reduce batch size since full model uses more memory
  learning_rate: 1e-5  # Lower LR for backbone fine-tuning
  backbone_lr: 5e-6  # Even lower LR for pre-trained backbone
  head_lr: 1e-4  # Higher LR for classification head
  num_epochs: 10  # More epochs for full fine-tuning
  warmup_steps: 2000  # More warmup for stable training
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  
# Learning rate scheduling
lr_schedule:
  type: "cosine_with_warmup"
  warmup_ratio: 0.1  # 10% of training for warmup
  min_lr_ratio: 0.01  # Minimum LR as 1% of initial
  
# Data processing
preprocessing:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
# Augmentation (more aggressive for full fine-tuning)
augmentation:
  rotation_degrees: 180
  horizontal_flip: true
  vertical_flip: true
  brightness_factor: 0.3  # Slightly more aggressive
  contrast_factor: 0.3
  gaussian_blur: true  # Add blur augmentation
  gaussian_noise: true  # Add noise augmentation

# STANDARDIZED 26-feature mapping (all models use this exact order)
standard_features:
  use_standard_mapping: true
  mapping_file: "standard_26_features.py"
  total_features: 26

# Experiment tracking
wandb:
  project: "galaxy-sommelier"
  entity: "sihany"
  log_freq: 50  # Log more frequently
  tags: ["mixed_dataset", "sdss_decals", "full_finetuning", "high_quality", "26_standardized_features"]

# Hardware
device: "cuda"
num_workers: 4
pin_memory: true

# Paths for outputs
checkpoint_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/models/mixed_high_quality"
results_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/results/mixed_high_quality"

# Initialization - start from head-trained model
pretrained_checkpoint: "/pscratch/sd/s/sihany/galaxy-sommelier-data/models/mixed_high_quality/best_model.pt"

# Logging
logging:
  level: "INFO"
  save_frequency: 2  # Save model every 2 epochs
  
# Early stopping
early_stopping:
  patience: 3  # Stop if no improvement for 3 epochs
  min_delta: 0.001  # Minimum improvement threshold
  monitor: "val_correlation"  # Monitor validation correlation 