# Galaxy Sommelier Triple Mixed SDSS+DECaLS+HST Head Training Configuration

# Data paths
data:
  scratch_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data"
  sdss_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/sdss"
  decals_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/decals"
  desi_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/desi"
  hst_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/hubble/images"
  processed_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/processed"
  catalogs_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs"
  catalog_name: "gz2_master_catalog_corrected.csv"  # SDSS catalog
  
  # Additional paths for triple mixed dataset
  sdss_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/gz2_master_catalog_corrected.csv"
  decals_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/gz_decals_volunteers_1_and_2.csv"
  hst_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/gz_hubble_main.csv"
  
# Mixed dataset configuration - STANDARDIZED to 26 features
mixed_data:
  use_mixed_dataset: true
  dataset_name: "TripleMixedDataset"
  feature_set: "standard_26"  # Use standardized 26-feature mapping
  
  # Dataset sizing: Use same SDSS+DECaLS selection as mixed_dataset.py + ALL HST
  # HST will use all available images (~113k)

# Model configuration - STANDARDIZED to 26 outputs
model:
  name: "facebook/dinov2-base"
  num_outputs: 26  # STANDARDIZED: All models use same 26 features
  dropout_rate: 0.2
  freeze_backbone: true  # Head training: freeze backbone

# Training parameters (same as successful mixed training)
training:
  batch_size: 32
  learning_rate: 1e-4
  num_epochs: 5
  warmup_steps: 1000
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  
# Data processing
preprocessing:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
# Augmentation
augmentation:
  rotation_degrees: 180
  horizontal_flip: true
  vertical_flip: true
  brightness_factor: 0.2
  contrast_factor: 0.2

# STANDARDIZED 26-feature mapping (all models use this exact order)
# Features will be output in the order defined in standard_26_features.py
standard_features:
  use_standard_mapping: true
  mapping_file: "standard_26_features.py"
  total_features: 26

# Early stopping - reasonable patience for head training
early_stopping:
  patience: 5  # Reasonable for 5-epoch head training
  min_delta: 0.001  
  monitor: "val_correlation"  # Focus on correlation improvement

# Experiment tracking
wandb:
  project: "galaxy-sommelier"
  entity: "sihany"
  log_freq: 100
  tags: ["triple_mixed_dataset", "sdss_decals_hst", "head_training", "26_standardized_features", "stable_config"]

# Hardware
device: "cuda"
num_workers: 4
pin_memory: true

# Paths for outputs
checkpoint_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/models/triple_mixed"
results_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/results/triple_mixed"

# Logging
logging:
  level: "INFO"
  save_frequency: 3  # Save more frequently to avoid losing progress 