# Galaxy Sommelier Triple Mixed SDSS+DECaLS+HST Full Fine-tuning Configuration

# Data paths
data:
  scratch_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data"
  sdss_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/sdss"
  decals_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/decals"
  desi_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/desi"
  hst_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/hubble/images"
  processed_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/processed"
  catalogs_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs"
  catalog_name: "gz2_master_catalog_corrected.csv"  # SDSS catalog
  
  # Additional paths for triple mixed dataset
  sdss_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/gz2_master_catalog_corrected.csv"
  decals_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/gz_decals_volunteers_1_and_2.csv"
  hst_catalog_path: "/pscratch/sd/s/sihany/galaxy-sommelier-data/catalogs/gz_hubble_main.csv"
  
# Mixed dataset configuration - STANDARDIZED to 26 features
mixed_data:
  use_mixed_dataset: true
  dataset_name: "TripleMixedDataset"
  feature_set: "standard_26"  # Use standardized 26-feature mapping
  
  # Dataset sizing: Use same SDSS+DECaLS selection as mixed_dataset.py + ALL HST
  # HST will use all available images (~113k)

# Model configuration - STANDARDIZED to 26 outputs
model:
  name: "facebook/dinov2-base"
  num_outputs: 26  # STANDARDIZED: All models use same 26 features
  dropout_rate: 0.2
  freeze_backbone: false  # Full finetuning: unfreeze backbone

# Training parameters for full fine-tuning (same as successful mixed training)
training:
  batch_size: 16  # Standard for full fine-tuning
  learning_rate: 1e-5  # Standard backbone fine-tuning LR
  backbone_lr: 5e-6  # Standard backbone LR
  head_lr: 1e-4  # Standard head LR
  num_epochs: 10  # Standard epochs
  warmup_steps: 2000  # Standard warmup
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  
# Learning rate scheduling
lr_schedule:
  type: "cosine_with_warmup"
  warmup_ratio: 0.1  # 10% of training for warmup
  min_lr_ratio: 0.01  # Minimum LR as 1% of initial
  
# Data processing
preprocessing:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
# Augmentation (more aggressive for full fine-tuning)
augmentation:
  rotation_degrees: 180
  horizontal_flip: true
  vertical_flip: true
  brightness_factor: 0.3  # Slightly more aggressive
  contrast_factor: 0.3
  gaussian_blur: true  # Add blur augmentation
  gaussian_noise: true  # Add noise augmentation

# STANDARDIZED 26-feature mapping (all models use this exact order)
# Features will be output in the order defined in standard_26_features.py
standard_features:
  use_standard_mapping: true
  mapping_file: "standard_26_features.py"
  total_features: 26

# Experiment tracking
wandb:
  project: "galaxy-sommelier"
  entity: "sihany"
  log_freq: 50  # Log more frequently
  tags: ["triple_mixed_dataset", "sdss_decals_hst", "full_finetuning", "26_standardized_features"]

# Hardware
device: "cuda"
num_workers: 4
pin_memory: true

# Paths for outputs
checkpoint_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/models/triple_mixed"
results_dir: "/pscratch/sd/s/sihany/galaxy-sommelier-data/results/triple_mixed"

# Initialization - start from head-trained model
pretrained_checkpoint: "/pscratch/sd/s/sihany/galaxy-sommelier-data/models/triple_mixed/best_model.pt"

# Logging
logging:
  level: "INFO"
  save_frequency: 2  # Save model every 2 epochs
  
# Early stopping
early_stopping:
  patience: 3  # Standard for fine-tuning
  min_delta: 0.001  # Minimum improvement threshold
  monitor: "val_correlation"  # Monitor validation correlation

# Galaxy Zoo tasks (core overlapping tasks across all 3 surveys)
galaxy_zoo_tasks:
  t01:
    responses: ["smooth", "features_or_disk", "star_or_artifact"]
    description: "Is the galaxy smooth and rounded, or does it have features?"
  t02:
    responses: ["edge_on_yes", "edge_on_no"]
    description: "Could this be a disk viewed edge-on?"
  t03:
    responses: ["bar_yes", "bar_no"]
    description: "Is there a bar feature through the center of the galaxy?"
  t04:
    responses: ["spiral_yes", "spiral_no"]
    description: "Is there any sign of a spiral arm pattern?"
  t05:
    responses: ["no_bulge", "obvious_bulge", "dominant_bulge"]
    description: "How prominent is the central bulge?" 